import type { NextPage } from 'next'
import Head from 'next/head'

export async function getServerSideProps() {
  const defaultEndpoint = 'http://localhost:4000/header'
  const res = await fetch(defaultEndpoint)
  const data = await res.json()

  return { props: { data } }
}

const Home: NextPage = (data) => {
  console.log("data", data)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       main
      </main>

      <footer>
        ciap
      </footer>
    </div>
  )
}

export default Home
